GorillaSwe/swipe-eats-backend

- Gemfile
- Gemfile.lock
- app/controllers/api/restaurants_controller.rb
- app/controllers/api/v1/test_controller.rb
- config/routes.rb
- test/controllers/api/restaurants_controller_test.rb
- test/controllers/api/v1/test_controller_test.rb
> [add]Google Places APIとの連携を実装

- app/controllers/api/restaurants_controller.rb
位置情報をクライアントサイドから受け取り、その情報をもとにレストラン情報を検索するよう修正しました。
> [update]位置情報をクライアントサイドから受け取る

- app/controllers/api/restaurants_controller.rb
> [add]クライアントサイドから受け取るパラメータを追加

- app/controllers/api/restaurants_controller.rb
> [add]クライアントサイドに送信する情報を追加

- app/controllers/api/restaurants_controller.rb
gemを用いると使用できない機能があるためGoogle Places APIを直接叩くよう修正しました。
> [refactor]gemを使わずGoogle Places APIを直接叩くよう修正

- bin/render-build.sh
> [hotfix]render-build.shの内容を修正

- Gemfile
- Gemfile.lock
- app/controllers/api/restaurants_controller.rb
- app/jobs/save_restaurant_job.rb
- app/models/photo.rb
- app/models/restaurant.rb
- db/migrate/20231019131452_create_restaurants.rb
- db/migrate/20231019131721_create_photos.rb
- db/migrate/20231019143630_change_url_column_type_in_photos.rb
- db/schema.rb
- test/fixtures/photos.yml
- test/fixtures/restaurants.yml
- test/jobs/save_restaurant_job_test.rb
- test/models/photo_test.rb
- test/models/restaurant_test.rb
> [add]Restaurantのテーブルを作成しました。

- app/controllers/api/restaurants_controller.rb
- app/jobs/save_restaurant_job.rb
Google Mapsのgemを使用するよう修正しました。
また、Photoモデルに保存するURLを、gemのfetch_urlメソッドを使用して取得するAPIキーが含まれないものに修正しました。
> [refactor]Google Mapsのgemを使用するよう修正

- app/controllers/api/users_controller.rb
> feat:ユーザーのCreateメソッドで登録済みでもstatus: :createdが返る

- app/controllers/api/favorites_controller.rb
> feat:お気に入りレストラン登録用のAPI作成

- app/controllers/api/favorites_controller.rb
- config/routes.rb
> faet:プロフィール画面用のAPI作成 #40

- app/controllers/api/favorites_controller.rb
- config/routes.rb
> feat:お気に入りレストラン削除用APIの作成 #51

- app/controllers/api/favorites_controller.rb
- app/controllers/api/restaurants_controller.rb
- config/routes.rb
- db/schema.rb
> feat:Favoriteのdestroyをrestaurantのplace_idをパラメータとして処理する #55

- app/controllers/api/restaurants_controller.rb
> feat:検索結果がない時などの表示修正 #61

- Gemfile
- Gemfile.lock
- app/controllers/api/favorites_controller.rb
- app/models/favorite.rb
- config/routes.rb
> feat:home画面用のAPIを実装 #64

- app/controllers/api/favorites_controller.rb
> feat:ホーム画面用のAPIを修正 #66

- app/controllers/api/favorites_controller.rb
- config/routes.rb
> feat:各ユーザー用のFavorite APIのメソッドを実装 #69

- app/controllers/api/favorites_controller.rb
- app/controllers/api/users_controller.rb
- config/routes.rb
> feat:プロフィール画面用のAPIに無限スクロールを実装 #75

- app/controllers/api/favorites_controller.rb
- app/controllers/api/follow_relationships_controller.rb
- app/controllers/api/users_controller.rb
- config/routes.rb
> refactor:コードをリファクタリング #78

- app/controllers/api/favorites_controller.rb
- app/controllers/api/restaurants_controller.rb
> refactor:APIでis_favoriteを返すように修正 #80

- db/migrate/20231212052100_remove_email_from_users.rb
- db/schema.rb
> feat:Usersテーブルからemailカラムを削除 #82

- app/controllers/api/favorites_controller.rb
- db/migrate/20231216093705_add_rating_and_comment_to_favorites.rb
- db/schema.rb
> feat:お気に入りにratingとcommentを追加 #88

- app/controllers/api/favorites_controller.rb
- app/controllers/api/restaurants_controller.rb
> feat:お気に入りのratingとcommentを修正 #90

- app/controllers/api/restaurants_controller.rb
> fix:Favorite登録時、ユーザー名が表示されない #93

- app/controllers/api/follow_relationships_controller.rb
- config/routes.rb
> feat:フォロワー、フォロー中画面用のAPIを作成 #96

- app/controllers/api/favorites_controller.rb
> fix:コメント編集時、空だと更新されない #98

- config/initializers/cors.rb
> feat:ドメイン取得に伴うCORSの修正 #101

- .github/workflows/main.yml
- config/database.yml.ci
> fix:GithubActionsがエラーとなる #112

- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
> document:READMEを修正 #115
